### ISSUE TITLE
 A little question

### ISSUE THREAD

**Issue by TheVetal** [dannyhann/protobuf_decoder#9]
Hi, I'm trying to decode protobuf and encountered the following problem: some lines are not fully decoded, and not all fields are found. For example, there is a line
000000010a0a2f08a8a489960315891674421d5ebe2342204528e8810230cc03380a4000489cd3afaa0650005a064e575333303960040a3008fb8f8996031540a572421d87e72442205628b8910230c603380a400048e5d4afaa0650005a0741464c3238303660000a3008fbf688960315e0d475421ddd313d4220342898f20130ee033812400048e6d4afaa0650005a0741464c3137313260000a2f0891c988960315f73277421da02b5442205228b8910230bc033800400048e5d4afaa0650005a06545941333032600012420a05080010e2710a05080110af020a04080210180a05080310a1030a0508041083030a05080510e4010a05080610bb010a04080710240a04080810090a040809100c800000000f677270632d7374617475733a300d0a
if I use your library the result is like this
[ParsedResult(field=0, wire_type='varint', data=0), ParsedResult(field=0, wire_type='varint', data=1), ParsedResult(field=1, wire_type='length_delimited', data=ParsedResults(results=[]))]
but if you go to the resource https://protobuf-decoder.netlify.app/ and decode this line there, then it finds more fields
Tell me, maybe I’m doing something wrong, why in some cases it decodes and finds all the fields, but in others it doesn’t. I would appreciate your answer

**Comment by dannyhann** [comment]
@TheVetal 
Oh, something wrong. 
I'll take a look and check it out.

**Comment by dannyhann** [comment]
@TheVetal 
I've checked it out!

First, when I tested with the values you provided, 
`000000010a0a2f08a8a489960315891674421d5ebe2342204528e8810230cc03380a4000489cd3afaa0650005a064e575333303960040a3008fb8f8996031540a572421d87e72442205628b8910230c603380a400048e5d4afaa0650005a0741464c3238303660000a3008fbf688960315e0d475421ddd313d4220342898f20130ee033812400048e6d4afaa0650005a0741464c3137313260000a2f0891c988960315f73277421da02b5442205228b8910230bc033800400048e5d4afaa0650005a06545941333032600012420a05080010e2710a05080110af020a04080210180a05080310a1030a0508041083030a05080510e4010a05080610bb010a04080710240a04080810090a040809100c800000000f677270632d7374617475733a300d0a`
my parser stopped immediately due to an unsupported wire_type. 
=> **I will improve this by showing an error along with the remaining bytes.**

---
When I checked the middle test value
~`000000010a`~`0a2f08a8a489960315891674421d5ebe2342204528e8810230cc03380a4000489cd3afaa0650005a064e575333303960040a3008fb8f8996031540a572421d87e72442205628b8910230c603380a400048e5d4afaa0650005a0741464c3238303660000a3008fbf688960315e0d475421ddd313d4220342898f20130ee033812400048e6d4afaa0650005a0741464c3137313260000a2f0891c988960315f73277421da02b5442205228b8910230bc033800400048e5d4afaa0650005a06545941333032600012420a05080010e2710a05080110af020a04080210180a05080310a1030a0508041083030a05080510e4010a05080610bb010a04080710240a04080810090a040809100c800000000f`~`677270632d7374617475733a300d0a`~
it shows the same result as the [website](https://protobuf-decoder.netlify.app/) you provided.

(The website also starts parsing from the 5~ byte, and `677270632d7374617475733a300d0a` is left over.)

---
I guess the binary might contain a separate protocol apart from the pure protobuf.
It might be good to divide the range while checking for meaningful values.

From what I see, the meaningful values are as follows:
`0a2f08a8a489960315891674421d5ebe2342204528e8810230cc03380a4000489cd3afaa0650005a064e57533330396004
0a3008fb8f8996031540a572421d87e72442205628b8910230c603380a400048e5d4afaa0650005a0741464c323830366000
0a3008fbf688960315e0d475421ddd313d4220342898f20130ee033812400048e6d4afaa0650005a0741464c313731326000
0a2f0891c988960315f73277421da02b5442205228b8910230bc033800400048e5d4afaa0650005a065459413330326000
12420a05080010e271
 0a05080110af02
 0a0408021018
 0a05080310a103
 0a050804108303
 0a05080510e401
 0a05080610bb01
 0a0408071024
 0a0408081009
 0a040809100c
`

Assuming the fields generally start from 1, below appears to be a continuous protobuf with fields 1, 2, and it seems like a repeated field.
Please check if it contains the data you need.

**Comment by TheVetal** [comment]
Hi, thanks for the help, yes all the data is there, and now everything works fine

**Comment by dannyhann** [comment]
I'm glad to hear that everything is working fine.  I'll go ahead and close the issue. 
Have a great weekend! 😀

**Comment by TheVetal** [comment]
Thank you, have a nice weekend too 👍
